#import "KLUserDefaults.h"

@implementation KLUserDefaults

static NSString *const kSuiteName = @"com.kai-lite.core";

+ (KLUserDefaults *)standardUserDefaults {
    static dispatch_once_t onceToken;
    static KLUserDefaults *defaults = nil;

    dispatch_once(&onceToken, ^{
        defaults = [[self alloc] initWithSuiteName:kSuiteName];
        [defaults registerDefaults];
    });

    return defaults;
}

- (void)registerDefaults {
    [self registerDefaults:@{
        // ---- SponsorBlock ----
        @"sponsorBlock":            @YES,
        @"sbSkipMode":              @0,
        @"sbDuration":              @5,
        @"sb_cat_sponsor":          @YES,
        @"sb_cat_selfpromo":        @YES,
        @"sb_cat_interaction":      @NO,
        @"sb_cat_intro":            @NO,
        @"sb_cat_outro":            @NO,
        @"sb_cat_preview":          @NO,
        @"sb_cat_music_offtopic":   @NO,
        @"sb_cat_filler":           @NO,

        // ---- Downloading ----
        @"downloadManager":         @YES,
        @"savePostInfo":            @NO,
        @"saveProfilePic":          @NO,
        @"saveCommentInfo":         @NO,
        @"preferStableVolume":      @NO,
        @"embedThumbnails":         @NO,
        @"embedCaptions":           @NO,

        // ---- Navigation bar ----
        @"hideCastButton":          @NO,
        @"hideNotificationsButton": @NO,
        @"hideSearchButton":        @NO,
        @"hideVoiceSearchButton":   @NO,
        @"stickyNavigationBar":     @NO,
        @"hideSubbar":              @NO,
        @"removeYouTubeLogo":       @NO,
        @"setPremiumLogo":          @NO,

        // ---- Feed ----
        @"removeAds":               @YES,
        @"hideShortsVideos":        @NO,
        @"keepShortsInSubs":        @NO,
        @"removeMoreTopics":        @NO,
        @"removeCommunityPosts":    @NO,
        @"removeMixes":             @NO,
        @"removeLiveVideos":        @NO,
        @"removeHorizontalFeeds":   @NO,
        @"removePlayables":         @NO,
        @"fixCovers":               @NO,

        // ---- Player ----
        @"ignoreAutoDubbed":        @NO,
        @"autoGeneratedCaptions":   @NO,
        @"speedControls":           @NO,
        @"muteButton":              @NO,
        @"lockButton":              @NO,
        @"hideAutoplaySwitch":      @NO,
        @"hideSubtitlesButton":     @NO,
        @"hidePrevNextButtons":     @NO,
        @"fastForwardRewind":       @NO,
        @"rememberLoopMode":        @NO,
        @"portraitFullscreen":      @NO,
        @"classicVideoQuality":     @NO,
        @"extraSpeedOptions":       @NO,
        @"removeDarkBackground":    @NO,
        @"hideEndScreens":          @NO,
        @"hideAutoPlayEnd":         @NO,
        @"disableFullscreenActions":@NO,
        @"disableSnackbars":        @NO,
        @"persistentProgressBar":   @NO,
        @"stockVolumeHUD":          @NO,
        @"noRelatedInOverlay":      @NO,

        // ---- Quality ----
        // Index 0 is Default and leaves YouTube's automatic quality unchanged.
        @"wiFiQualityIndex":        @0,
        @"cellQualityIndex":        @0,

        // ---- Account ----
        // Temporary compatibility patch for signing into a sideloaded build.
        @"googleSignInPatch":       @NO,

        // ---- Shorts ----
        @"shortsOnlyMode":          @NO,
        @"limitShorts":             @NO,
        @"shortsEnableProgress":    @NO,
        @"shortsSpeedUp":           @NO,
        @"pinchToFullscreen":       @NO,
        @"shortsToRegular":         @NO,
        @"shortsRemoveLive":        @NO,
        @"hideShortsLogo":          @NO,
        @"shortsHideSearch":        @YES,

        // ---- Tab bar ----
        @"translucentTabBar":       @YES,
        @"removeTabLabels":         @NO,
        @"removeTabIndicators":     @NO,

        // ---- Interface ----
        @"oledTheme":               @NO,
        @"oledKeyboard":            @NO,
        @"hideSearchHistory":       @NO,
        @"removeGuidelines":        @NO,
        @"stickCommentsHeader":     @NO,
        @"hideCommentsHeader":      @NO,
        @"oldPlaylistMinibar":      @NO,
        @"disableRTL":              @NO,
    }];
}

@end
